baseURL = 'https://lephuduc.github.io/'
languageCode = 'en-us'
title = "You just landed on Jinn's site, let's find out.."
theme = 'hugo-theme-reimu'

[markup.highlight]
guessSyntax = true
noClasses = false